### ISSUE TITLE
Basic features checklist

### ISSUE THREAD

**Issue by IljaKroonen** [IljaKroonen/rules_kotlin_skylark#2]
- [x] Generate source jars
- [ ] Support for Java compiler plugins (required for Dagger 2)
- [ ] Support for Kotlin compiler plugins (required for allopen)
- [x] Resources attribute on kt_jvm_library
- [ ] Friend attribute on kt_jvm_test
- [x] Data attribute in kt_jvm_library
- [x] 1.8 JVM target
